### PR TITLE
Initial version

### PR DESCRIPTION
**Pull request by chrisdc**
Hello, here's some initial code for the tabbable dropdowns. I've tried to minimize the number of elements theme authors will have to customize, but it should all be working well. I'd be interested in hearing if people would like to see more documentation and/or use of ARIA roles and properties here.

### CODE REVIEW

**Comment by chrisdc** [comment]
Ok, I see @joedolson has put something up instead. Shall I close this and/or make a vanilla javascript version of that?

**Comment by joedolson** [comment]
We've discussed that there's actually lots of room for multiple interpretations of dropdowns, and we want to have multiple versions to provide easy variety for users.

What we're going to do is have each unique pattern for a dropdown in a subdirectory within the main repo; we can't automatically merge this request, but if you drop it into a subdirectory in the repo it shouldn't be a problem.

**Comment by chrisdc** [comment]
Hi, my current pull request includes jQuery and vanilla js. Since you've
got the jQuery sorted I might refocus on just vanilla for now. I also have
a version using object orientated JavaScript that could be worth including
at some point.

**Comment by chrisdc** [comment]
Sorry for the delay, as mentioned above I've focused on vanilla js and moved everything into a subdirectory. I've also expanded style.css and added a header.php

**Pull request merged**
